// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package firebase

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// GetUserID provides a mock function for the type MockInterface
func (_mock *MockInterface) GetUserID(r *http.Request) string {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockInterface_GetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserID'
type MockInterface_GetUserID_Call struct {
	*mock.Call
}

// GetUserID is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockInterface_Expecter) GetUserID(r interface{}) *MockInterface_GetUserID_Call {
	return &MockInterface_GetUserID_Call{Call: _e.mock.On("GetUserID", r)}
}

func (_c *MockInterface_GetUserID_Call) Run(run func(r *http.Request)) *MockInterface_GetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInterface_GetUserID_Call) Return(s string) *MockInterface_GetUserID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockInterface_GetUserID_Call) RunAndReturn(run func(r *http.Request) string) *MockInterface_GetUserID_Call {
	_c.Call.Return(run)
	return _c
}
