// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFirebaseInterface creates a new instance of MockFirebaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFirebaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFirebaseInterface {
	mock := &MockFirebaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFirebaseInterface is an autogenerated mock type for the FirebaseInterface type
type MockFirebaseInterface struct {
	mock.Mock
}

type MockFirebaseInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFirebaseInterface) EXPECT() *MockFirebaseInterface_Expecter {
	return &MockFirebaseInterface_Expecter{mock: &_m.Mock}
}

// GetUserID provides a mock function for the type MockFirebaseInterface
func (_mock *MockFirebaseInterface) GetUserID(r *http.Request) string {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFirebaseInterface_GetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserID'
type MockFirebaseInterface_GetUserID_Call struct {
	*mock.Call
}

// GetUserID is a helper method to define mock.On call
//   - r
func (_e *MockFirebaseInterface_Expecter) GetUserID(r interface{}) *MockFirebaseInterface_GetUserID_Call {
	return &MockFirebaseInterface_GetUserID_Call{Call: _e.mock.On("GetUserID", r)}
}

func (_c *MockFirebaseInterface_GetUserID_Call) Run(run func(r *http.Request)) *MockFirebaseInterface_GetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockFirebaseInterface_GetUserID_Call) Return(s string) *MockFirebaseInterface_GetUserID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFirebaseInterface_GetUserID_Call) RunAndReturn(run func(r *http.Request) string) *MockFirebaseInterface_GetUserID_Call {
	_c.Call.Return(run)
	return _c
}
