all: false
dir: '{{.InterfaceDir}}/mocks' # Place mocks in a "mocks" subdirectory
filename: "mock_{{.InterfaceName}}.go" # Generate files like "mock_firebaseinterface.go"
force-file-write: false
formatter: goimports
log-level: info
structname: "Mock{{.InterfaceName}}" # Struct names like "MockFirebaseInterface"
pkgname: "mocks" # Use "mocks" as the package name for all generated mocks
recursive: false
template: testify

packages:
    trainiverse-backend/internal/db:
        interfaces:
            DBInterface:
    trainiverse-backend/internal/interfaces:
        interfaces:
            CheckinInterface:
    trainiverse-backend/internal/firebase:
        interfaces:
            FirebaseInterface: