all: false
dir: '{{.InterfaceDir}}/mocks'
filename: "mock_{{.InterfaceName}}.go"
log-level: info
structname: "Mock{{.InterfaceName}}"
recursive: false

packages:
    trainiverse-backend/internal/db:
        interfaces:
            DBInterface:
    trainiverse-backend/internal/interfaces:
        interfaces:
            CheckinInterface:
    trainiverse-backend/internal/firebase:
        interfaces:
            FirebaseInterface:
    trainiverse-backend/internal/utils:
        interfaces:
            ExifDecoderInterface:
            ImageSaverInterface:
