// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package utils

import (
	"io"

	"github.com/rwcarlsen/goexif/exif"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExifDecoderInterface creates a new instance of MockExifDecoderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExifDecoderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExifDecoderInterface {
	mock := &MockExifDecoderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExifDecoderInterface is an autogenerated mock type for the ExifDecoderInterface type
type MockExifDecoderInterface struct {
	mock.Mock
}

type MockExifDecoderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExifDecoderInterface) EXPECT() *MockExifDecoderInterface_Expecter {
	return &MockExifDecoderInterface_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type MockExifDecoderInterface
func (_mock *MockExifDecoderInterface) Decode(file io.Reader) (*exif.Exif, error) {
	ret := _mock.Called(file)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 *exif.Exif
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader) (*exif.Exif, error)); ok {
		return returnFunc(file)
	}
	if returnFunc, ok := ret.Get(0).(func(io.Reader) *exif.Exif); ok {
		r0 = returnFunc(file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exif.Exif)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = returnFunc(file)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExifDecoderInterface_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockExifDecoderInterface_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - file io.Reader
func (_e *MockExifDecoderInterface_Expecter) Decode(file interface{}) *MockExifDecoderInterface_Decode_Call {
	return &MockExifDecoderInterface_Decode_Call{Call: _e.mock.On("Decode", file)}
}

func (_c *MockExifDecoderInterface_Decode_Call) Run(run func(file io.Reader)) *MockExifDecoderInterface_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExifDecoderInterface_Decode_Call) Return(exif1 *exif.Exif, err error) *MockExifDecoderInterface_Decode_Call {
	_c.Call.Return(exif1, err)
	return _c
}

func (_c *MockExifDecoderInterface_Decode_Call) RunAndReturn(run func(file io.Reader) (*exif.Exif, error)) *MockExifDecoderInterface_Decode_Call {
	_c.Call.Return(run)
	return _c
}
