// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package utils

import (
	"mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// NewMockImageSaverInterface creates a new instance of MockImageSaverInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageSaverInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageSaverInterface {
	mock := &MockImageSaverInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageSaverInterface is an autogenerated mock type for the ImageSaverInterface type
type MockImageSaverInterface struct {
	mock.Mock
}

type MockImageSaverInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageSaverInterface) EXPECT() *MockImageSaverInterface_Expecter {
	return &MockImageSaverInterface_Expecter{mock: &_m.Mock}
}

// SaveImage provides a mock function for the type MockImageSaverInterface
func (_mock *MockImageSaverInterface) SaveImage(file multipart.File, originalName string, folder string, userID string) error {
	ret := _mock.Called(file, originalName, folder, userID)

	if len(ret) == 0 {
		panic("no return value specified for SaveImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(multipart.File, string, string, string) error); ok {
		r0 = returnFunc(file, originalName, folder, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageSaverInterface_SaveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveImage'
type MockImageSaverInterface_SaveImage_Call struct {
	*mock.Call
}

// SaveImage is a helper method to define mock.On call
//   - file multipart.File
//   - originalName string
//   - folder string
//   - userID string
func (_e *MockImageSaverInterface_Expecter) SaveImage(file interface{}, originalName interface{}, folder interface{}, userID interface{}) *MockImageSaverInterface_SaveImage_Call {
	return &MockImageSaverInterface_SaveImage_Call{Call: _e.mock.On("SaveImage", file, originalName, folder, userID)}
}

func (_c *MockImageSaverInterface_SaveImage_Call) Run(run func(file multipart.File, originalName string, folder string, userID string)) *MockImageSaverInterface_SaveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 multipart.File
		if args[0] != nil {
			arg0 = args[0].(multipart.File)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockImageSaverInterface_SaveImage_Call) Return(err error) *MockImageSaverInterface_SaveImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageSaverInterface_SaveImage_Call) RunAndReturn(run func(file multipart.File, originalName string, folder string, userID string) error) *MockImageSaverInterface_SaveImage_Call {
	_c.Call.Return(run)
	return _c
}
