// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"trainiverse-backend/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCheckoutInterface creates a new instance of MockCheckoutInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckoutInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckoutInterface {
	mock := &MockCheckoutInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckoutInterface is an autogenerated mock type for the CheckoutInterface type
type MockCheckoutInterface struct {
	mock.Mock
}

type MockCheckoutInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckoutInterface) EXPECT() *MockCheckoutInterface_Expecter {
	return &MockCheckoutInterface_Expecter{mock: &_m.Mock}
}

// SaveCheckout provides a mock function for the type MockCheckoutInterface
func (_mock *MockCheckoutInterface) SaveCheckout(checkoutData models.CheckoutData) error {
	ret := _mock.Called(checkoutData)

	if len(ret) == 0 {
		panic("no return value specified for SaveCheckout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.CheckoutData) error); ok {
		r0 = returnFunc(checkoutData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCheckoutInterface_SaveCheckout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCheckout'
type MockCheckoutInterface_SaveCheckout_Call struct {
	*mock.Call
}

// SaveCheckout is a helper method to define mock.On call
//   - checkoutData models.CheckoutData
func (_e *MockCheckoutInterface_Expecter) SaveCheckout(checkoutData interface{}) *MockCheckoutInterface_SaveCheckout_Call {
	return &MockCheckoutInterface_SaveCheckout_Call{Call: _e.mock.On("SaveCheckout", checkoutData)}
}

func (_c *MockCheckoutInterface_SaveCheckout_Call) Run(run func(checkoutData models.CheckoutData)) *MockCheckoutInterface_SaveCheckout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.CheckoutData
		if args[0] != nil {
			arg0 = args[0].(models.CheckoutData)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCheckoutInterface_SaveCheckout_Call) Return(err error) *MockCheckoutInterface_SaveCheckout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCheckoutInterface_SaveCheckout_Call) RunAndReturn(run func(checkoutData models.CheckoutData) error) *MockCheckoutInterface_SaveCheckout_Call {
	_c.Call.Return(run)
	return _c
}
