// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDBInterface creates a new instance of MockDBInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBInterface {
	mock := &MockDBInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDBInterface is an autogenerated mock type for the DBInterface type
type MockDBInterface struct {
	mock.Mock
}

type MockDBInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBInterface) EXPECT() *MockDBInterface_Expecter {
	return &MockDBInterface_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockDBInterface
func (_mock *MockDBInterface) Exec(query string, args ...any) (sql.Result, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(query, args)
	} else {
		tmpRet = _mock.Called(query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...any) (sql.Result, error)); ok {
		return returnFunc(query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...any) sql.Result); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = returnFunc(query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDBInterface_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockDBInterface_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *MockDBInterface_Expecter) Exec(query interface{}, args ...interface{}) *MockDBInterface_Exec_Call {
	return &MockDBInterface_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockDBInterface_Exec_Call) Run(run func(query string, args ...any)) *MockDBInterface_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockDBInterface_Exec_Call) Return(result sql.Result, err error) *MockDBInterface_Exec_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockDBInterface_Exec_Call) RunAndReturn(run func(query string, args ...any) (sql.Result, error)) *MockDBInterface_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type MockDBInterface
func (_mock *MockDBInterface) Prepare(query string) (*sql.Stmt, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 *sql.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*sql.Stmt, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *sql.Stmt); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDBInterface_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockDBInterface_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - query string
func (_e *MockDBInterface_Expecter) Prepare(query interface{}) *MockDBInterface_Prepare_Call {
	return &MockDBInterface_Prepare_Call{Call: _e.mock.On("Prepare", query)}
}

func (_c *MockDBInterface_Prepare_Call) Run(run func(query string)) *MockDBInterface_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDBInterface_Prepare_Call) Return(stmt *sql.Stmt, err error) *MockDBInterface_Prepare_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *MockDBInterface_Prepare_Call) RunAndReturn(run func(query string) (*sql.Stmt, error)) *MockDBInterface_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockDBInterface
func (_mock *MockDBInterface) Query(query string, args ...any) (*sql.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(query, args)
	} else {
		tmpRet = _mock.Called(query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...any) (*sql.Rows, error)); ok {
		return returnFunc(query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...any) *sql.Rows); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = returnFunc(query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDBInterface_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockDBInterface_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *MockDBInterface_Expecter) Query(query interface{}, args ...interface{}) *MockDBInterface_Query_Call {
	return &MockDBInterface_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockDBInterface_Query_Call) Run(run func(query string, args ...any)) *MockDBInterface_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockDBInterface_Query_Call) Return(rows *sql.Rows, err error) *MockDBInterface_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockDBInterface_Query_Call) RunAndReturn(run func(query string, args ...any) (*sql.Rows, error)) *MockDBInterface_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockDBInterface
func (_mock *MockDBInterface) QueryRow(query string, args ...any) *sql.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(query, args)
	} else {
		tmpRet = _mock.Called(query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(string, ...any) *sql.Row); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

// MockDBInterface_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockDBInterface_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *MockDBInterface_Expecter) QueryRow(query interface{}, args ...interface{}) *MockDBInterface_QueryRow_Call {
	return &MockDBInterface_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockDBInterface_QueryRow_Call) Run(run func(query string, args ...any)) *MockDBInterface_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockDBInterface_QueryRow_Call) Return(row *sql.Row) *MockDBInterface_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockDBInterface_QueryRow_Call) RunAndReturn(run func(query string, args ...any) *sql.Row) *MockDBInterface_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}
