name: CI-CD Action

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  pre-build-validations:
    name: Pre-build Validations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4

      - name: Run go mod tidy
        run: go mod tidy

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::warning::Found uncommitted changes after running 'go mod tidy'"
            git diff go.mod
            echo "::warning::Please run 'go mod tidy' locally and commit the changes"
            exit 0  # Don't fail the build, just warn
          fi

      - name: Validate go.mod and go.sum
        run: |
          go mod verify
          go mod download

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4

      - name: Clean Go module cache
        run: go clean -modcache

      - name: Download Go module dependencies
        run: go mod download

      - name: Build project to verify dependencies
        env:
          GOFLAGS: "-mod=mod"
        run: go build ./...

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run -v

  commitlint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Commitlint
        run: npx commitlint --from=origin/${{github.base_ref}} --to=HEAD --verbose

  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: [ lint, pre-build-validations, commitlint ]
    if: github.ref == 'refs/heads/dev'
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
