name: CI-CD Action

on:
  pull_request:
    branches: [ dev, master ]

jobs:
  build:
    name: Build Go Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'

      - name: Cache Go modules and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.2

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Install dependencies
        run: go mod download

      - name: Build project
        run: go build -o output/main .
